### ISSUE TITLE
Missing parameter for "PV Pro" packages, Error "[getMeteoblueData]: pv queries require kwp parameter"

### ISSUE THREAD

**Issue by owkowo69** [ice987987/ioBroker.meteoblue#187]
### The problem

I've installed the adapter to retrieve forcast "PV Pro", but in the instance-settings there's no parameter to set the kWp.

Starting the Adapter quits with error "[getMeteoblueData]: pv queries require kwp parameter"

### Version of Node.js

18.19.0

### Version of ioBroker js-controller

6.0.9

### Version of "meteoblue"-adapter

v0.1.0-beta.11

### Version of "admin"-adapter

7.0.22

### Operating system incl. version running ioBroker

Linux docker (official image - v9.0.1)

### Checklist of files to include below

- [x] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by owkowo69** [comment]
[meteoblue-debug.log](https://github.com/user-attachments/files/16729772/meteoblue-debug.log)

**Comment by ice987987** [comment]
kwp=1&slope=20&facing=180&power_efficiency=0.9&tracker=1 are missing
